In [49]:
# importing libraries

import pandas as pd
import wget as wget
import numpy as np

# Q1. Pandas version #

In [5]:
pd.__version__

'2.2.2'

# Getting the data #

In [11]:
wget.download("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv", "car_fuel_efficiency.csv")

'car_fuel_efficiency.csv'

In [14]:
df = pd.read_csv("car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

# Q2. Records count #

In [16]:
df.shape

(9704, 11)

# Q3. Fuel types #

In [18]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

# Q4. Missing values #

In [19]:
missing_cols = df.columns[df.isnull().any()]
num_missing_cols = len(missing_cols)
num_missing_cols

4

# Q5. Max fuel efficiency #

In [22]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

# Q6. Median value of horsepower #

In [23]:
df['horsepower'].median()

149.0

In [24]:
df['horsepower'].mode()[0]

152.0

In [25]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [26]:
df['horsepower'].median()

152.0

# Q7. Sum of weights #

In [28]:
df_asia = df[df['origin'] == 'Asia']
df_asia

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [29]:
df_selected = df[['vehicle_weight', 'model_year']]
df_selected.head()

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009

In [46]:
df_values = df_selected.head(7)
df_values

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [32]:
X = df_values.values

In [34]:
X_transposed = X.T
X_transposed

array([[3413.43375861, 3149.66493422, 3079.03899737, 2542.39240183,
        3460.87098999, 2484.88398604, 3006.54228722],
       [2003.        , 2007.        , 2018.        , 2009.        ,
        2009.        , 2008.        , 2012.        ]])

In [36]:
XTX = X_transposed @ X
XTX

array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

In [ ]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 1.12464107e-06, -1.68991495e-06],
       [-1.68991495e-06,  2.57468996e-06]])

In [38]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [39]:
w = XTX_inv @ X_transposed @ y
w

array([0.07099685, 0.41931263])

In [42]:
round(w.sum(), 2)

0.49

In [48]:
round(w.sum(), 1)

0.5